### ISSUE TITLE
Mint FREEOS failed with assertion failure: Incorrect mintfee has been paid.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#48] opened 2022-08-29 04:44 UTC
29/8/22 freeosgov2 frontend v0.2.4 backend v0.9.44 iter 461597
Account: verovera 'v' verified, registered, Min Mintfee=1 FREEOS, Mint Amt= 1 POINT
Available POINTs: 14479.0000 POINT, Locked POINTs: 1746.3432 POINT, MFF: 99.0000 POINT, FREEBI: 62.1934 FREEBI, FREEOS: 6.2345 FREEOS.
When minting POINTs to FREEOS using only the mintfeefree allowance. On Clicking Mint FREEOS->Assertion failure: Incorrect mint fee has been paid.
As user's mintfeefree allowance (99 POINTs) is > mint amount (1 POINT). Expecting the MintFREEOS to be successful using the freepoints only and NO mintfee will be required.

![Freeos Governance dApp 29-08-2022 15-51-20](https://user-images.githubusercontent.com/77765830/187119557-b7029279-3248-4d2b-8297-b690c3ebc96e.png)
<img width="475" alt="Screen Shot 2022-08-29 at 3 47 25 PM" src="https://user-images.githubusercontent.com/77765830/187122975-9f9b4c99-fd89-4075-aa96-37b138030ae7.png">

**Comment by tommccann777** [comment] 2022-08-29 09:06
I can't reproduce the problem exactly as I don't have the keys to verovera. I will use vivvestin instead.

**Comment by stuartmcphersonflipmind** [comment] 2022-09-01 20:21
Changes to the AirClaim Points have made this issue void, closing

**Closed as completed by stuartmcphersonflipmind** 2022-09-01 20:21 UTC
